builds:
  - id: "smtpmock-build"
    dir: cmd
    binary: smtpmock
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/mocktools/go-smtp-mock/v2/cmd/version.Version={{.Version}}
      - -X github.com/mocktools/go-smtp-mock/v2/cmd/version.GitCommit={{.Commit}}
      - -X github.com/mocktools/go-smtp-mock/v2/cmd/version.BuildTime={{.Date}}
archives:
  - id: smtpmock-archive
    builds:
      - smtpmock-build
    name_template: "smtpmock_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
